### ISSUE TITLE
 ISO_3166-1_alpha-2 SX (Sint Maarten) is missing 

### ISSUE THREAD

**Issue by jorbie** [sshaw/normalize_country#6]
thx for your great work so far!
i found another country code:
`NormalizeCountry("SX")
 => nil 
`
https://en.wikipedia.org/wiki/ISO_3166-2:SX

best

**Comment by sshaw** [comment]
Hi thanks, fixed in v0.2.3.

**Comment by jorbie** [comment]
nice, thanks a lot :)
